version: "3"

services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  app:
    build: .
    command: npm start
    environment:
        - DB=${DB}
        - PORT=${PORT}
        - HOST=${HOST}
    ports:
      - "3000:3000"
    volumes:
      - ./usr/app
